# Generated by Django 5.2 on 2025-04-12 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccionesMitigacion',
            fields=[
                ('mitigacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_mitigacion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'acciones_mitigacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('categoria_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=85)),
            ],
            options={
                'db_table': 'categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriasRiesgos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'categorias_riesgos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('proyecto_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proyecto', models.CharField(max_length=255)),
                ('estado_proyecto', models.CharField(max_length=45)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('presupuesto', models.FloatField()),
                ('moneda', models.CharField(max_length=15)),
                ('duracion_estimada', models.IntegerField()),
                ('unidad_duracion', models.CharField(max_length=15)),
                ('cantidad_equipo', models.IntegerField()),
                ('ubicacion_geografica', models.CharField(max_length=150)),
                ('fecha_creacion', models.DateField()),
            ],
            options={
                'db_table': 'proyectos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Riesgos',
            fields=[
                ('riesgo_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_riesgo', models.CharField(max_length=85)),
                ('estado_riesgo', models.CharField(max_length=85)),
                ('probabilidad', models.IntegerField()),
                ('impacto', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'riesgos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoProyecto',
            fields=[
                ('tipo_proyecto_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tipo_proyecto',
                'managed': False,
            },
        ),
    ]
